# Generated by Django 4.2 on 2023-04-18 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_students_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Registration',
            new_name='RegistrationNo',
        ),
    ]
